name: Generate Snake

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push: {branches: ["master", "main"]}
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./contribution-snake/github-contribution-grid-snake.gif
          svg_out_path: ./contribution-snake/github-contribution-grid-snake.svg?palette=github-dark
