name: Generate Snake

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */8 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push: {branches: ["master", "main"]}
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: Generate Snake
        uses: Platane/snk/svg-only@v2.0.0-rc.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./contribution-snake/github-contribution-grid-snake.svg
            ./contribution-snake/github-contribution-grid-snake-dark.svg?palette=github-dark
